### ISSUE TITLE
haproxy was not installed?

### ISSUE THREAD

**Issue by hopewise** [Oefenweb/ansible-haproxyctl#2]
I tried your role, however, when I ssh to the instance, I get this:

```
$ haproxy -v
-bash: haproxy: command not found
```

Any idea?

Here is how I've used the role:
- name: Install HAProxy dependencies
  hosts: haproxy
  remote_user: admin
  sudo: yes
  roles:
  - role: tersmitten.haproxyctl

**Comment by tersmitten** [comment]
This role does not install [haproxy](https://github.com/Oefenweb/ansible-haproxy), it installs [haproxyctl](https://github.com/flores/haproxyctl). `haproxyctl` is only for monitoring `haproxy`
